export default {
    avatar: require('../../assets/image/user.png'),
    speaking: require('../../assets/image/speaking.png'),
    listening: require('../../assets/image/listening.png'),
    reading: require('../../assets/image/reading.png'),
    writing: require('../../assets/image/writing.png'),
    crown: require('../../assets/image/crown.png'),
    background: require('../../assets/image/background.png'),
    setting: require('../../assets/image/setting.png'),
    privacy: require('../../assets/image/padlock.png'),
    trick_icon: require('../../assets/image/vacancy.png'),
    background_lesson: require('../../assets/image/background_lesson.png'),
    japanese: require('../../assets/image/japan.png'),
    announce: require('../../assets/image/bell.png'),
    home: require('../../assets/image/tabbar/home.png'),
    book: require('../../assets/image/tabbar/book.png'),
    practice: require('../../assets/image/tabbar/medal.png'),
    profile: require('../../assets/image/tabbar/user.png'),
    back: require('../../assets/image/tabbar/back.png'),
    lesson: require('../../assets/image/lesson.png'),
    trick: require('../../assets/image/bulb.png'),
    read: require('../../assets/image/read.png'),
    speak: require('../../assets/image/talking.png'),
    sound: require('../../assets/image/sound.png'),
    quiz: require('../../assets/image/quiz.png'),
    grammar: require('../../assets/image/grammar.png'),
    vocab: require('../../assets/image/dictionary.png'),
    edit: require('../../assets/image/edit.png'),
    search: require('../../assets/image/search.png'),
    google: require('../../assets/image/google.png'),
    fb: require('../../assets/image/facebook.png'),
    regis: require('../../assets/image/regis.png'),
    true: require('../../assets/image/good.png'),
    false: require('../../assets/image/angry.png'),
    logo: require('../../assets/image/readingcat.png')

}